//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoes.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductOrder = new HashSet<ProductOrder>();
        }
    
        public string Article { get; set; }
        public string Name { get; set; }
        public int Unit_Id { get; set; }
        public decimal Price { get; set; }
        public int Supplier_Id { get; set; }
        public int Manufactirere_Id { get; set; }
        public int Category_Id { get; set; }
        public int Discount { get; set; }
        public int Count { get; set; }
        public string Discription { get; set; }
        public string PhotoPath { get; set; }
        public string FullPhotoPath 
        { 
            get
            {
                if (PhotoPath != "")

                    return $"\\Images\\{PhotoPath}";
                else
                    return $"\\Images\\picture.png";
            } 
        }
    
        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual ICollection<ProductOrder> ProductOrder { get; set; }
    }
}
